targets:
  $default:
    builders:
      dorm|entity:
        enabled: true
      dorm|schema:
        enabled: true
      dorm|db:
        enabled: true
      dorm|migration:
        enabled: true
      dorm|schema_diff:
        enabled: true

builders:
  entity:
    import: "package:dorm/tool/entity_generator.dart"
    builder_factories: ["entityGeneratorBuilder"]
    build_extensions: { ".dart": [".orm.g.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["dorm|schema"]

  schema:
    import: "package:dorm/tool/schema_generator.dart"
    builder_factories: ["schemaGeneratorBuilder"]
    build_extensions: { ".dart": [".schema.g.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".orm.g.dart"]
    runs_before: ["dorm|db"]

  db:
    import: "package:dorm/tool/db_generator.dart"
    builder_factories: ["dbGeneratorBuilder"]
    build_extensions: { ".dart": [".db.g.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".schema.g.dart"]

  migration:
    import: "package:dorm/tool/migration_generator.dart"
    builder_factories: ["migrationGeneratorBuilder"]
    build_extensions: { ".dart": [".migration.g.dart"] }
    auto_apply: dependents

  schema_diff:
    import: "package:dorm/tool/schema_diff_generator.dart"
    builder_factories: ["schemaDiffGeneratorBuilder"]
    build_extensions: { ".dart": [".diff.g.dart"] }
    auto_apply: dependents
