targets:
  $default:
    builders:
      dorm|entity:
        enabled: true
      dorm|migration:
        enabled: true
      dorm|db_schema:
        enabled: true
      dorm|db:
        enabled: true
      dorm|schema_diff:
        enabled: true

builders:
  entity:
    import: "package:dormql/tool/entity_generator.dart"
    builder_factories: ["entityGeneratorBuilder"]
    build_extensions: { ".dart": [".orm.g.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["dorm|migration"]

  migration:
    import: "package:dormql/tool/migration_generator.dart"
    builder_factories: ["migrationGeneratorBuilder"]
    build_extensions: { ".dart": [".migration.g.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".orm.g.dart"]
    runs_before: ["dorm|db_schema"]

  db_schema:
    import: "package:dormql/tool/db_schema_generator.dart"
    builder_factories: ["dbSchemaGeneratorBuilder"]
    build_extensions: { ".dart": [".schemas.g.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".orm.g.dart"]
    runs_before: ["dorm|db"]

  db:
    import: "package:dormql/tool/db_generator.dart"
    builder_factories: ["dbGeneratorBuilder"]
    build_extensions: { ".dart": [".db.g.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".schemas.g.dart"]

  schema_diff:
    import: "package:dormql/tool/schema_diff_generator.dart"
    builder_factories: ["schemaDiffGeneratorBuilder"]
    build_extensions: { ".dart": [".diff.g.dart"] }
    auto_apply: dependents
