name: dormql_analyzer_plugin
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  analysis_server_plugin: ^0.3.4
  analyzer_plugin: ^0.13.11
  analyzer: ^9.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
