name: Release package:dormql_analyzer_plugin

on:
  push:
    tags:
      - "dormql_analyzer_plugin-v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
    - name: clean directory
      run: |
        rm -rf packages
        rm -rf docs
        mv example/db_postgres_dorm_example/* example/
        rm -rf example/db_postgres_dorm_example

    - name: publish
      run: |
        cd packages/dormql_analyzer_plugin
        dart pub get
        dart format .
        dart pub publish --dry-run
        dart pub publish -f
